language: go
sudo: false

go:
  - 1.7

install:
  - go get -d -t ./...
  - (cd $GOPATH/src/github.com/ready-steady/hdf5 && make install)

script:
  - make build
  - make test

notifications:
  email: false
